version: "3.6"
services:
  postgres:
    build: "./internal/database/"
    restart: "always"
    environment:
      POSTGRES_DB: "Bank"
      POSTGRES_USER: "kulakov"
      POSTGRES_PASSWORD: 1234
    ports: 
      - 3350:5432

  golang:
    build: "./"
    restart: "always"
    ports:
      - 3351:3351